const fs = require('fs'),
  Sequelize = require('sequelize');
const Op = Sequelize.Op;

module.exports = {
  "development": {
    "username": "us8vbkxrnjjlbhw3",
    "password":"UrFV0MhmzfEg5wJUn7b",
    "database": "btdwd0frc",
    "host": "btdwd0frc-mysql.services.clever-cloud.com",
    "dialect": "mysql",
    timezone : "-07:00",
    $eq: Op.eq,
    $ne: Op.ne,
    $gte: Op.gte,
    $gt: Op.gt,
    $lte: Op.lte,
    $lt: Op.lt,
    $not: Op.not,
    $in: Op.in,
    $notIn: Op.notIn,
    $is: Op.is,
    $like: Op.like,
    $notLike: Op.notLike,
    $iLike: Op.iLike,
    $notILike: Op.notILike,
    $regexp: Op.regexp,
    $notRegexp: Op.notRegexp,
    $iRegexp: Op.iRegexp,
    $notIRegexp: Op.notIRegexp,
    $between: Op.between,
    $notBetween: Op.notBetween,
    $overlap: Op.overlap,
    $contains: Op.contains,
    $contained: Op.contained,
    $adjacent: Op.adjacent,
    $strictLeft: Op.strictLeft,
    $strictRight: Op.strictRight,
    $noExtendRight: Op.noExtendRight,
    $noExtendLeft: Op.noExtendLeft,
    $and: Op.and,
    $or: Op.or,
    $any: Op.any,
    $all: Op.all,
    $values: Op.values,
    $col: Op.col
  },
  "test": {
    "username": "us8vbkxrnjjlbhw3",
    "password":"UrFV0MhmzfEg5wJUn7b",
    "database": "btdwd0frc",
    "host": "btdwd0frc-mysql.services.clever-cloud.com",
    "dialect": "mysql"
  },
  "production": {
    "username": "us8vbkxrnjjlbhw3",
    "password": "UrFV0MhmzfEg5wJUn7b",
    "database": "btdwd0frc",
    "host": "btdwd0frc-mysql.services.clever-cloud.com",
    "dialect": "mysql",
    timezone : "+08:00",
    $eq: Op.eq,
    $ne: Op.ne,
    $gte: Op.gte,
    $gt: Op.gt,
    $lte: Op.lte,
    $lt: Op.lt,
    $not: Op.not,
    $in: Op.in,
    $notIn: Op.notIn,
    $is: Op.is,
    $like: Op.like,
    $notLike: Op.notLike,
    $iLike: Op.iLike,
    $notILike: Op.notILike,
    $regexp: Op.regexp,
    $notRegexp: Op.notRegexp,
    $iRegexp: Op.iRegexp,
    $notIRegexp: Op.notIRegexp,
    $between: Op.between,
    $notBetween: Op.notBetween,
    $overlap: Op.overlap,
    $contains: Op.contains,
    $contained: Op.contained,
    $adjacent: Op.adjacent,
    $strictLeft: Op.strictLeft,
    $strictRight: Op.strictRight,
    $noExtendRight: Op.noExtendRight,
    $noExtendLeft: Op.noExtendLeft,
    $and: Op.and,
    $or: Op.or,
    $any: Op.any,
    $all: Op.all,
    $values: Op.values,
    $col: Op.col
  }
}
